-- This SQL script removes all country-specific data in order to make the install looks as generic as possible.

DELETE FROM report_rights WHERE rightname = 'print_vaccine_Order_Requisition';
DELETE FROM report_rights WHERE rightname = 'Print Order Requisition';
DELETE FROM report_rights WHERE rightname = 'Print Issue report';
DELETE FROM report_rights WHERE rightname = 'vims_distribution';

DELETE FROM rights WHERE name = 'MANAGE_SUPPLYLINE';
DELETE FROM rights WHERE name = 'MANAGE_ELMIS_INTERFACE';
DELETE FROM rights WHERE name = 'CONFIGURE_HELP_CONTENT';
DELETE FROM rights WHERE name = 'ACCESS_ILS_GATEWAY';
DELETE FROM rights WHERE name = 'SERVICE_VENDOR_RIGHT';
DELETE FROM rights WHERE name = 'MANAGE_DONOR';
DELETE FROM rights WHERE name = 'MANAGE_SEASONALITY_RATIONING';
DELETE FROM rights WHERE name = 'MANAGE_VACCINE_DISEASE_LIST';
DELETE FROM rights WHERE name = 'VIEW_STOCK_IMBALANCE_REPORT';
DELETE FROM rights WHERE name = 'MANAGE_VACCINE_PRODUCTS_CONFIGURATION';
DELETE FROM rights WHERE name = 'ACCESS_NEW_DASHBOARD';
DELETE FROM rights WHERE name = 'VIEW_FACILITY_REPORT';
DELETE FROM rights WHERE name = 'VIEW_ORDER_REPORT';
DELETE FROM rights WHERE name = 'VIEW_RNR_FEEDBACK_REPORT';
DELETE FROM rights WHERE name = 'VIEW_ADJUSTMENT_SUMMARY_REPORT';
DELETE FROM rights WHERE name = 'VIEW_REPORTING_RATE_REPORT';
DELETE FROM rights WHERE name = 'VIEW_AVERAGE_CONSUMPTION_REPORT';
DELETE FROM rights WHERE name = 'VIEW_SUPPLY_STATUS_REPORT';
DELETE FROM rights WHERE name = 'VIEW_CONSUMPTION_REPORT';
DELETE FROM rights WHERE name = 'VIEW_DISTRICT_CONSUMPTION_REPORT';
DELETE FROM rights WHERE name = 'VIEW_MAILING_LABEL_REPORT';
DELETE FROM rights WHERE name = 'VIEW_STOCKED_OUT_REPORT';
DELETE FROM rights WHERE name = 'VIEW_SUMMARY_REPORT';
DELETE FROM rights WHERE name = 'VIEW_ORDER_FILL_RATE_REPORT';
DELETE FROM rights WHERE name = 'VIEW_REGIMEN_SUMMARY_REPORT';
DELETE FROM rights WHERE name = 'VIEW_DISTRICT_FINANCIAL_SUMMARY_REPORT';
DELETE FROM rights WHERE name = 'VIEW_DASHBOARD_POC';
DELETE FROM rights WHERE name = 'VIEW_LAB_EQUIPMENT_LIST_REPORT';
DELETE FROM rights WHERE name = 'VIEW_LAB_EQUIPMENTS_BY_FUNDING_SOURCE';
DELETE FROM rights WHERE name = 'VIEW_ORDER_FILL_RATE_SUMMARY_REPORT';
DELETE FROM rights WHERE name = 'VIEW_LAB_EQUIPMENTS_BY_LOCATION_REPORT';
DELETE FROM rights WHERE name = 'VIEW_TIMELINESS_REPORT';
DELETE FROM rights WHERE name = 'VIEW_SEASONALITY_RATIONING_REPORT';
DELETE FROM rights WHERE name = 'VIEW_PIPELINE_EXPORT';
DELETE FROM rights WHERE name = 'VIEW_CCE_STORAGE_CAPACITY_REPORT';
DELETE FROM rights WHERE name = 'VIEW_COLD_CHAIN_EQUIPMENT_LIST_REPORT';
DELETE FROM rights WHERE name = 'VIEW_REPAIR_MANAGEMENT_REPORT';
DELETE FROM rights WHERE name = 'VIEW_VACCINE_REPLACEMENT_PLAN_SUMMARY';
DELETE FROM rights WHERE name = 'VIEW_REQUISITION_REPORT';
DELETE FROM rights WHERE name = 'VIEW_STOCK_ON_HAND_REPORT';
DELETE FROM rights WHERE name = 'print_vaccine_Order_Requisition';
DELETE FROM rights WHERE name = 'Print Order Requisition';
DELETE FROM rights WHERE name = 'Print Issue report';
DELETE FROM rights WHERE name = 'vims_distribution';
DELETE FROM rights WHERE name = 'CREATE_IVD';
DELETE FROM rights WHERE name = 'APPROVE_IVD';
DELETE FROM rights WHERE name = 'VIEW_IVD';
DELETE FROM rights WHERE name = 'VIEW_ORDER_REQUISITION';
DELETE FROM rights WHERE name = 'VIEW_PENDING_REQUEST';
DELETE FROM rights WHERE name = 'CREATE_ORDER_REQUISITION';
DELETE FROM rights WHERE name = 'MASS_DISTRIBUTION';
DELETE FROM rights WHERE name = 'MANAGE_CUSTOM_REPORTS';
DELETE FROM rights WHERE name = 'VIEW_CUSTOM_REPORTS';
DELETE FROM rights WHERE name = 'VIEW_FACILITY_INTEGRATION';
DELETE FROM rights WHERE name = 'VIEW_PRODUCT_RATIONING';
DELETE FROM rights WHERE name = 'MANAGE_EQUIPMENT_SERVICING';
DELETE FROM rights WHERE name = 'VIEW_HELP';
DELETE FROM rights WHERE name = 'MANAGE_IVD_TEMPLATES';
DELETE FROM rights WHERE name = 'VIEW_USER_SUMMARY_REPORT';
DELETE FROM rights WHERE name = 'MANAGE_DEMOGRAPHIC_PARAMETERS';
DELETE FROM rights WHERE name = 'MANAGE_DEMOGRAPHIC_ESTIMATES';
DELETE FROM rights WHERE name = 'FINALIZE_DEMOGRAPHIC_ESTIMATES';
DELETE FROM rights WHERE name = 'UNLOCK_FINALIZED_DEMOGRAPHIC_ESTIMATES';

UPDATE configuration_settings
SET value = '/public/pages/index.html'
WHERE key = 'LOGIN_SUCCESS_DEFAULT_LANDING_PAGE';

UPDATE configuration_settings
SET isconfigurable = FALSE
WHERE groupname IN ('Dashboard','GENERAL','Order Export','R & R','VACCINE');