INSERT INTO "dhis2_products" VALUES ('Amoxicillin 125mg/5ml susp', '10040010MD', NULL);
INSERT INTO "dhis2_products" VALUES ('Amoxicillin 250mg cap', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Amoxicillin 250mg disp tablet', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Amoxicillin 250mg/5ml susp', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Ampicillin 1g vial', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Ceftriaxone 1g vial', '10060016MD', NULL);
INSERT INTO "dhis2_products" VALUES ('Ceftriaxone 250mg vial', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Chlorhexidine cream', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Depo provera', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Emergency contraception', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Gentamicin 40mg/ml amp', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Implants', '10010194AC', NULL);
INSERT INTO "dhis2_products" VALUES ('IUDs', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Magnesium Sulphate', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Metronidazole 5mg/ml vial', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Microgynon', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Misoprostol', '', NULL);
INSERT INTO "dhis2_products" VALUES ('ORS', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Oxytocin Injection', '10060044MD', NULL);
INSERT INTO "dhis2_products" VALUES ('Procaine Benzylpenicillin 1g amp', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Procaine Benzylpenicillin 3g amp', '', NULL);
INSERT INTO "dhis2_products" VALUES ('Zinc sulphate 20mg disp tablet', '10010129AC', NULL);