#!/bin/bash

BULKDATA_DIR=$HOME/BulkData
DATA_COUNT=1000

if [ -d "$BULKDATA_DIR" ]; then
    	rm -rf $BULKDATA_DIR
	mkdir $BULKDATA_DIR
fi

	echo -e "Product Code,Alternate Item Code,Product Manufacturer ID,Manufacturer Product Code,Manufacturer Bar Code,MoH Bar Code,GTIN,Product Type,Product Primary Name,Product Full Name,Generic Name,Alternate Name,Description,Product Strength,Product Form,Dosage Units,Dispensing Units,Doses Per Dispensing Unit,Pack Size,Alternate Pack Size,Store Refrigerated,Store Room Temperature,Product Is Hazardous,Product Is Flammable,Product Is Controlled Substance,Product Is Light Sensitive,Approved By WHO,Contraceptive CYP,Pack Length,Pack Width,Pack Height,Pack Weight,Packs Per Carton,Carton Length,Carton Width,Carton Height,Cartons Per Pallet,Expected Shelf Life,Special Storage Instructions,Special Transport Instructions,Product Is Active,Product Is Full Supply,Is A Tracer Product,Pack Rounding Threshold,Can Round To Zero,Has Been Archived" >> $BULKDATA_DIR/products.csv

	echo -e "Product Code,Program Code,Doses Per Month,Is Active" >> $BULKDATA_DIR/program_product.csv

	echo -e "INSERT INTO facility_approved_products(facilityTypeId, programProductId, maxMonthsOfStock) values" >> $BULKDATA_DIR/facility_approved_products.sql

	echo -e "Facility Code,Facility Name,Facility Description,GLN,Facility Main Phone,Facility Fax,Facility Address1,Facility Address2,Geographic Zone ID,Facility Type Code,Catchment Population,Facility LAT,Facility LONG,Facility Altitude,Facility Operated By,Cold Storage Gross Capacity,Cold Storage Net Capacity,Facility Supplies Others,Facility Is SDP,Facility Has Electricity,Facility Is Online,Facility Has Electronic SCC,Facility Has Electronic DAR,Is Active,Facility Go Live Date,Facility Go Down Date,Is Satellite Facility,Satellite Parent ID,Facility Comments,Data Reportable" >> $BULKDATA_DIR/facilities.csv

	echo -e "Facility Code,Program Code,Program Is Active" >> $BULKDATA_DIR/program_supported.csv

	echo -e "INSERT INTO requisition_groups ( code ,name,description,supervisoryNodeId )values
('RG2','Requistion Group 2','Supports EM(Q1M)',(select id from  supervisory_nodes where code ='N1')),
('RG1','Requistion Group 1','Supports EM(Q2M)',(select id from  supervisory_nodes where code ='N2'));" >> $BULKDATA_DIR/requisition_groups.sql

	echo -e "INSERT INTO requisition_group_members ( requisitionGroupId ,facilityId )values" >> $BULKDATA_DIR/requisition_group_members.sql

    for ((i = 10; i <= $DATA_COUNT ; i++))
    do
        echo -e "P$i,A$i,Glaxo and Smith,a,a,Test,G100,antibiotic,Indinavir 400mg Tablets,TDF/FTC/EFV,TDF/FTC/EFV,TDF/FTC/EFV,TDF/FTC/EFV,300/200/600,Tablet,MG,Btl of 180Tabl,90,10,10,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,10,10,0,20,10,2,2,10,10,10,10,10,10,TRUE,TRUE,FALSE,1,FALSE,TRUE" >> $BULKDATA_DIR/products.csv

	echo -e "P$i,HIV,30,TRUE" >> $BULKDATA_DIR/program_product.csv
	
	PRODUCTID=`expr $i - 9`
	echo -e "(1, (select id from program_products where programId=1 and productId=$PRODUCTID), 3)," >> $BULKDATA_DIR/facility_approved_products.sql
    
	echo -e "F$i,F$i Village Dispensary,IT department,G7645,9876234981,fax,A,B,1,warehouse,333,22.1,1.2,3.3,NGO,9.9,6.6,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,11/11/12,11/11/1887,TRUE,,fc,TRUE" >> $BULKDATA_DIR/facilities.csv

	echo -e "F$i,HIV,TRUE" >> $BULKDATA_DIR/program_supported.csv

	echo -e "((select id from  requisition_groups where code ='RG1'),(select id from  facilities where code ='F$i'))," >> $BULKDATA_DIR/requisition_group_members.sql
	done
