version: '3.3'
services:
  postgres:
    image: "postgres:9.4"
    container_name: open-lmis-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_DB=open_lmis
    ports:
      - 5432:5432

