INSERT INTO "alerts" VALUES ('RNR_REJECTED','NOTIFICATION',false,false,NULL, NULL,NULL);

INSERT INTO "alerts" VALUES ('SUBMIT_RNR_REMINDER','NOTIFICATION',true,false,NULL, 'SUBMIT_RNR_REMINDER_EMAIL_MESSAGE_TEMPLATE', NULL);
INSERT INTO "alerts" VALUES ('STOCK_STATUS','NOTIFICATION',false,true,NULL, NULL,'STOCK_STATUS_SMS_MESSAGE_TEMPLATE');

INSERT INTO "alerts" VALUES ('RATIONING','NOTIFICATION',true,true,NULL, 'RATIONING_EMAIL_MESSAGE_TEMPLATE','RATIONING_SMS_MESSAGE_TEMPLATE');
