ALTER TABLE donors
ADD code VARCHAR (50) NOT NULL UNIQUE,
ADD createdBy INTEGER,
ADD createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD modifiedBy INTEGER,
ADD modifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;