-- Organize notification email and sms message templates

--delete unused template messages
delete from configuration_settings where key in ('SMS_EMERGENCY_REQUISITION','EMAIL_EMERGENCY_REQUISITION','EMAIL_REQUISITION_PENDING','SMS_REQUISITION_REJECTED',
'EMAIL_REQUISITION_REJECTED','SMS_FACILITY_STOCKED_OUT','EMAIL_FACILITY_STOCKED_OUT','SMS_REQUISITION_APPROVED','EMAIL_REQUISITION_APPROVED','SMS_COMMODITY_RATIONED');

--Group all email message templates under 'Notification - Email'
update configuration_settings
set groupname = 'Notificaiton - Email' where key in ('PRODUCT_RECALLED_EMAIL_MESSAGE_TEMPLATE',
'REQUISITION_PENDING_EMAIL_MESSAGE_TEMPLATE',
'REQUISITION_REJECTED_EMAIL_MESSAGE_TEMPLATE',
'STOCK_STATUS_EMAIL_MESSAGE_TEMPLATE',
'SUBMIT_RNR_REMINDER_EMAIL_MESSAGE_TEMPLATE',
'RATIONING_EMAIL_MESSAGE_TEMPLATE',
'LATE_RNR_NOTIFICATION_EMAIL_TEMPLATE',
'EMAIL_SUBJECT_APPROVAL',
'EMAIL_TEMPLATE_APPROVAL'
);

--Group all sms message templates under 'Notification - SMS'
update configuration_settings
set groupname = 'Notificaiton - SMS' where key in ('PRODUCT_RECALLED_SMS_MESSAGE_TEMPLATE',
'REQUISITION_PENDING_SMS_MESSAGE_TEMPLATE',
'REQUISITION_REJECTED_SMS_MESSAGE_TEMPLATE',
'STOCK_STATUS_SMS_MESSAGE_TEMPLATE',
'SUBMIT_RNR_REMINDER_SMS_MESSAGE_TEMPLATE',
'RATIONING_SMS_MESSAGE_TEMPLATE',
'LATE_RNR_NOTIFICATION_SMS_TEMPLATE'
);
