CREATE TABLE facility (
    id SERIAL PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(250),
    gln VARCHAR(30),
    main_phone VARCHAR(20),
    fax VARCHAR(20),
    address1 VARCHAR(50),
    address2 VARCHAR(50),
    geographic_zone_id INTEGER NOT NULL REFERENCES geographic_zone(id),
    type_id INTEGER NOT NULL REFERENCES facility_type(id),
    catchment_population INTEGER,
    latitude NUMERIC(8,4),
    longitude NUMERIC(8,4),
    altitude NUMERIC(8,4),
    operated_by_id INTEGER REFERENCES facility_operator(id),
    cold_storage_gross_capacity NUMERIC(8,4),
    cold_storage_net_capacity NUMERIC(8,4),
    supplies_others BOOLEAN,
    is_sdp BOOLEAN NOT NULL,
    is_online BOOLEAN,
    is_satellite BOOLEAN,
    satellite_parent_code VARCHAR(6) REFERENCES facility(code),
    has_electricity BOOLEAN,
    has_electronic_scc BOOLEAN,
    has_electronic_dar BOOLEAN,
    active BOOLEAN NOT NULL,
    go_live_date DATE NOT NULL,
    go_down_date DATE,
    comment  TEXT,
    data_reportable BOOLEAN,
    modified_by VARCHAR(50),
    modified_date TIMESTAMP DEFAULT  CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uc_facility_code ON facility(LOWER(code));