drop table if exists requisition_line_items;
create table requisition_line_items (
id serial primary key,
rnrId int not null references requisition(id),
productCode varchar(50) not null references product(code),
product varchar(250),
beginningBalance integer,
quantityReceived integer,
quantityDispensed integer,
estimatedConsumption integer,
stockInHand integer,
quantityRequested integer,
reasonForRequestedQuantity text,
calculatedOrderQuantity integer,
quantityApproved integer,
lossesAndAdjustments integer,
reasonForLossesAndAdjustments text,
newPatientCount integer,
stockOutDays integer,
normalizedConsumption integer,
amc numeric(8,4),
maxStockQuantity integer,
packsToShip integer,
cost numeric(8, 4),
remarks text,
dosesPerMonth integer not null,
dosesPerDispensingUnit integer not null,
modifiedBy varchar(50),
modifiedDate timestamp  DEFAULT  CURRENT_TIMESTAMP
);